apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"boot001dep","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"boot001kube"}},"template":{"metadata":{"labels":{"app":"boot001kube"}},"spec":{"containers":[{"image":"ys0915/k8s_boot:latest","imagePullPolicy":"Always","name":"boot-container","ports":[{"containerPort":7777}]}]}}}}
  creationTimestamp: "2025-11-05T01:58:43Z"
  generation: 1
  name: boot001dep
  namespace: default
  resourceVersion: "45934"
  uid: f262f9eb-964b-47e7-b398-fa7d36dca9b3
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: boot001kube
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: boot001kube
    spec:
      containers:
      - image: kdg1644/k8s_boot:latest
        imagePullPolicy: Always
        name: boot-container
        ports:
        - containerPort: 7777
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-11-05T02:00:24Z"
    lastUpdateTime: "2025-11-05T02:00:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-05T01:58:43Z"
    lastUpdateTime: "2025-11-05T02:00:24Z"
    message: ReplicaSet "boot001dep-74db5bfb9f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
